import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";
import { FavoritesProvider } from "./contexts/FavoritesContext";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Harry Potter App by Galvão",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Navbar />

          <FavoritesProvider>{children}</FavoritesProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
